### ISSUE TITLE
Lost connection to MySQL server at 'reading initial communication packet'

### ISSUE THREAD

**Issue by SuperCoolGuy855** [mirromutth/mysql-action#16]
I tried to import a SQL file:
`mysql -h 127.0.0.1 -u admin -p123456789 < recovery.sql`
but it returns "Lost connection to MySQL server at 'reading initial communication packet'" and I don't know what to do.
Some pointers would be appreciated. Thanks

**Comment by TiraTom** [comment]
How about waiting the mysql-action complete boot up? 
After I had added `sleep 15` before `mysql -h 127.0.0.1 -u ...`, I didn't encounter the error.
(I'm sorry but I have no idea how to write a script check if their operations have completed well..)

**Comment by fcidade** [comment]
I added a simple wait loop on my GA, if anyone is interested:
```sh
until mysqladmin ping -h 127.0.0.1 --silent; do
  echo 'waiting for mysql to start...'
  sleep 2
done
```
